# Generated by Django 3.1.4 on 2020-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_auto_20201215_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuario',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
