# Generated by Django 3.1.4 on 2020-12-15 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda_app', '0003_auto_20201215_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='nombre',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='usuario',
            new_name='pais',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
