# Generated by Django 3.1.4 on 2021-01-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0007_auto_20210102_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='artista',
        ),
    ]
