# Generated by Django 3.1.4 on 2021-01-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0009_artista_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
    ]
